name: golang-ci

on: [push, pull_request]

jobs:

  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@latest
        with:
          go-version: ^1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@latest

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test $(go list ./...)

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - name: golangci-lint
        uses: golangci/golangci-lint-action@latest
        with:
          version: latest
